default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: publish_data_beta_development

test:
  <<: *default
  database: publish_data_beta_test

integration:
  <<: *default

production: &production
  <<: *default
  database: publish_data_beta_production
  username: publish_data_beta
  password: <%= ENV['PUBLISH_DATA_BETA_DATABASE_PASSWORD'] %>

staging:
  <<: *production
