default: &default
  network_timeout: 5

development:
  <<: *default
  namespace: development
  host: redis
  port: 6379

test:
  <<: *default
  namespace: test
  host: localhost
  port: 6379

staging:
  <<: *default
  url: '<%= JSON.parse(ENV["VCAP_SERVICES"] || "{}")
                .dig("redis", 0, "credentials", "uri") %>'

production:
  <<: *default
  url: '<%= JSON.parse(ENV["VCAP_SERVICES"] || "{}")
                .dig("redis", 0, "credentials", "uri") %>'
